server.port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/tea
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true

  sql.init.mode: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB


