server.port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  #datasource:
   # url: jdbc:postgresql://db:5432/tea
    #driver-class-name: org.postgresql.Driver
    #username: postgres
 #   password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true

  sql.init.mode: always

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB


